config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root	'static_pages#home'
  get 	'/register',	to: 'homes#new'
  resources :homes
  resources :lopers

  get '/login',		to: 'sessions#new'
  post '/login',	to: 'sessions#create'
  delete '/logout',	to: 'sessions#destroy'

  post 'homes/:id', to: 'homes#post'
  post 'lopers/:id',to: 'lopers#ronde'
  post '/',         to: 'lopers#loop'


# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    &#169; Vincent De Clercq
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" style="background:#003466;">
  <div class="container">
    <%= link_to "home konvent", "http://homekonvent.be", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Startpagina",   root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Homes", homes_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Home <%= @current_user.naam %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Status", current_user %></li>
              <li><%= link_to "Instellingen", edit_home_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log uit", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
        <li><img src="http://hkcentraal.ugent.be/static/images/schilden/konvent.png"></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  	<title><%= yield(:title) %> | 12-urenloop HK</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>